### ISSUE TITLE
[RFC] Add some default github template for PR / Issues?

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/codingstyle#16]
As github is on :fire: since the "dear github" letter, they ship a lots of feature, and one of them is issue/PR template: https://github.com/blog/2111-issue-and-pull-request-templates

We could benefit from a good default in our projects, as it's very common to read crappy junk PR, without any description other than the commit message (yeah thx for nothing), no deployment infos, no "how to test", no link to the original issue... 

We also don't have a common way to communicate a PR status (WIP in the title, a "do not merge plz" somewhere, etc).

Here is a good example of what I want: https://gist.github.com/Lordnibbler/11002759

**Comment by pyrech** [comment]
yeah :+1: for this. We can also make use at the same time of the new `.github` folder to put in it those templates :sparkles:

**Comment by welcoMattic** [comment]
:star2:  :+1: :star2:
